name: ML_intro
channels:
  - conda-forge
dependencies:
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - matplotlib=3.9.1
  - numpy=2.0.1
  - pandas=2.2.2
  - pip
  - plotly=5.23.0
  - python=3.11
  - scikit-learn=1.5.1
  - scipy=1.14.0
